services:

  proxitok:
    container_name: proxitok
    image: quay.io/pussthecatorg/proxitok:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - "LATTE_CACHE=/cache"
      - "API_CACHE=redis"
      - "REDIS_HOST=proxitok-redis"
      - "REDIS_PORT=6379"
      - "API_SIGNER_URL=http://proxitok-signer:8080/signature"
    volumes:
      - "proxitok-cache:/cache"
    depends_on:
      - proxitok-redis
      - proxitok-signer

  proxitok-redis:
    container_name: proxitok-redis
    image: docker.io/redis:6-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  proxitok-signer:
    container_name: proxitok-signer
    image: ghcr.io/pablouser1/signtok:master

volumes:
  proxitok-cache:
